### ISSUE TITLE
Qwen2.5-7B-Instruct+SEALONG

### ISSUE THREAD

**Issue by gom168** [SihengLi99/SEALONG#3]
作者你好，看到实验中有基于Qwen2.5-7B-Instruct+SEALONG的实验，这里看xtuner官方库中还没有支持Qwen2.5，想请问你们这里的具体实现细节

**Comment by SihengLi99** [comment]
您好，

感谢您对我们的项目感兴趣！

为了支持 Qwen 2.5 系列的实验，您可能需要安装特定版本的库，我们的设置为：
transformers == 4.42.4
tokenizers == 0.20.0rc1

祝好！


gx7 ***@***.***> 于2024年11月18日周一 12:43写道：

**Comment by gom168** [comment]
您好，感谢您的回复。能再请问一下为了支持 Qwen 2.5 系列的实验，你们的xtuner版本吗？

**Comment by SihengLi99** [comment]
您好，我们使用的是 V0.1.23

gx7 ***@***.***>于2024年11月25日 周一10:49写道：
